services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - DB_USERNAME=root
      - DB_PASSWORD=12345678
      - DB_DATABASE=database_production
      - DB_HOST=127.0.0.1
      - JWT_ACCESS_SECRET=dsf34rp34tPJG
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: database_production
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: